FROM debian:bullseye
RUN apt-get -y update \
&&  apt-get -y install binutils \
                       dnsutils \
                       net-tools \
                       psmisc \
                       telnet \
                       tcpdump \
                       vim
